import Link from "next/link";
import type { Metadata } from "next";
import ScreenshotGallery from "@/app/components/ScreenshotGallery";

export const metadata: Metadata = {
  title: "Data Architecture Management – Dongjin Cho",
  description:
    "Internal tool for automating database standardization, schema verification, and data quality validation at Alian.",
};

const techs = ["Next.js 14", "React 18", "TypeScript", "Tailwind CSS", "Prisma", "PostgreSQL", "Zustand", "Zod"];

const features = [
  {
    title: "Standard Dictionary Management",
    description:
      "Manages standard words, terms, and domains systematically. Words are registered with Korean name, English name, and abbreviations, then combined to generate standard terms. Domains define data type, length, and allowed value rules.",
  },
  {
    title: "Schema Definition Management",
    description:
      "Manages definitions at database, table, and column levels. Each column maps to a standard term, with PK/FK/AK settings, NULL constraints, and personal data / encryption flags.",
  },
  {
    title: "Automated Schema Verification",
    description:
      "Automatically compares definition documents with the actual database schema to find mismatches. Replaced manual line-by-line review — verifying 1,300+ columns in seconds instead of hours.",
  },
  {
    title: "Validation Template Engine",
    description:
      "Reusable SQL validation templates per domain with placeholder substitution. 34 templates auto-generate 784 validation queries across hundreds of target columns.",
  },
  {
    title: "Data Quality Validation",
    description:
      "Executes auto-generated validation queries against live databases. Supports batch and individual column validation with real-time result tracking and history export.",
  },
  {
    title: "Multi-Database Integration",
    description:
      "Manages PostgreSQL and MySQL schemas in a single application using Prisma's multi-schema support, eliminating the need for separate management per database type.",
  },
];

const stack = [
  {
    title: "Frontend",
    items: [
      "Next.js 14 (App Router)",
      "React 18",
      "Tailwind CSS + Headless UI",
      "Zustand (global state)",
      "Custom hooks for search & pagination",
    ],
  },
  {
    title: "Backend",
    items: [
      "Next.js Route Handlers",
      "Prisma ORM (multi-schema: PostgreSQL + MySQL)",
      "Iron Session authentication",
      "bcrypt password hashing",
      "Zod schema validation",
    ],
  },
  {
    title: "Data & Validation",
    items: [
      "Standard Word → Term → Domain linked structure",
      "DB schema auto-comparison engine",
      "ERD Excel parsing & verification",
      "SQL template-based query generation",
      "xlsx-js-style Excel export",
    ],
  },
];

const screenshots = [
  {
    src: "/experience/data-architecture/dictionary-word.png",
    alt: "Standard Word Dictionary",
    label: "Standard Words",
    heading: "Standard Word Dictionary",
    badge: "Dictionary",
    description:
      "Manages 1,824 standard words with Korean/English name and abbreviation mappings. Supports search, pagination, and Excel download for maintaining naming standards across the organization.",
  },
  {
    src: "/experience/data-architecture/dictionary-term.png",
    alt: "Standard Term Dictionary",
    label: "Standard Terms",
    heading: "Standard Term Dictionary",
    badge: "Dictionary",
    description:
      "Manages 5,875 standard terms generated by combining standard words. Each term links to a domain for automatic data type and length mapping. Abbreviations serve as physical column names.",
  },
  {
    src: "/experience/data-architecture/definition-column.png",
    alt: "Column Definition",
    label: "Column Definition",
    heading: "Schema Definition",
    badge: "Definition",
    description:
      "Three-level definition management (DB > Table > Column) with standard term mapping, PK/FK/AK constraints, NULL settings, and personal data / encryption classification.",
  },
  {
    src: "/experience/data-architecture/verification-schema.png",
    alt: "Schema Verification",
    label: "Schema Verification",
    heading: "Schema Verification Results",
    badge: "Core Feature",
    description:
      "Automated comparison of definition documents against live database schemas. Verified 1,315 columns with 1,261 successes and 54 failures — categorized by error type (data type mismatch, FK inconsistency, undefined columns).",
  },
  {
    src: "/experience/data-architecture/validation-template.png",
    alt: "Validation Templates",
    label: "Validation Templates",
    heading: "Validation Template Engine",
    badge: "Automation",
    description:
      "Domain-specific SQL templates with placeholder-based auto-substitution. Covers amount ranges, date formats, code validity, and more. 34 templates generate 784 validation queries automatically.",
  },
  {
    src: "/experience/data-architecture/validation-data.png",
    alt: "Data Quality Validation",
    label: "Data Validation",
    heading: "Data Quality Validation",
    badge: "Quality",
    description:
      "Executes generated validation queries against live databases. Supports batch validation (Validate All) and individual runs with domain/table/column filtering. Results tracked with history and Excel export.",
  },
  {
    src: "/experience/data-architecture/history-verification.png",
    alt: "Verification History",
    label: "History",
    heading: "Verification History",
    badge: "Tracking",
    description:
      "All verification results are stored as history. View results by verification type (standard terms, schema, ERD) with total/pass/fail statistics, enabling data quality improvement tracking over time.",
  },
];

const challenges = [
  {
    title: "Manual Verification Inefficiency",
    description:
      "Comparing definition documents with physical schemas line by line required excessive time and caused frequent human errors across 1,300+ columns. Built an automated comparison engine that queries the DB schema directly, reducing verification from hours to seconds.",
  },
  {
    title: "ERD–Definition Mismatch",
    description:
      "ERDs were maintained as Excel files separately from definitions, causing frequent undetected inconsistencies. Created an Excel parsing engine that auto-extracts table/column info and matches against definitions to surface discrepancies immediately.",
  },
  {
    title: "Repetitive Data Quality Checks",
    description:
      "Writing validation queries manually for each domain-specific rule across hundreds of columns was impractical. Designed a template engine with placeholder substitution — 34 templates now auto-generate 784 validation queries.",
  },
  {
    title: "Heterogeneous Database Management",
    description:
      "Multiple database types (PostgreSQL, MySQL) in production required separate management workflows. Leveraged Prisma's multi-schema capability to unify schema management within a single application.",
  },
];

export default function DataArchitecturePage() {
  return (
    <div className="min-h-screen bg-gray-950 text-white">
      {/* Top nav */}
      <nav className="sticky top-0 z-50 border-b border-gray-800 bg-gray-950/80 px-6 backdrop-blur-md">
        <div className="mx-auto flex h-14 max-w-5xl items-center justify-between">
          <Link href="/#experience" className="cursor-pointer font-mono text-sm text-gray-400 transition-colors hover:text-purple-400">
            ← Back to Experience
          </Link>
          <span className="font-mono text-xs tracking-widest text-purple-400">// Alian · Database Architect</span>
        </div>
      </nav>

      {/* Hero */}
      <section className="relative overflow-hidden border-b border-gray-800 px-6 py-24 md:py-32">
        <div className="pointer-events-none absolute inset-0 flex items-center justify-center">
          <div className="h-96 w-96 rounded-full bg-purple-500/5 blur-3xl" />
        </div>
        <div className="relative mx-auto max-w-5xl">
          <p className="mb-4 font-mono text-sm uppercase tracking-widest text-purple-400">
            // Alian · Database Architect
          </p>
          <h1 className="text-4xl font-bold tracking-tight md:text-6xl">
            Data Architecture Management
          </h1>
          <p className="mt-6 max-w-2xl text-base leading-relaxed text-gray-400 md:text-lg">
            An internal tool I built to automate database standardization management for our main project.
            Previously, all data standard verification was done 100% manually — reviewing thousands of terms
            and columns one by one. This tool automated the entire process, minimizing human errors
            and cutting verification time from hours to seconds across 1,300+ columns.
          </p>
          <div className="mt-8 flex flex-wrap gap-2">
            {techs.map((t) => (
              <span
                key={t}
                className="rounded-full border border-purple-400/30 bg-purple-400/5 px-3 py-1 font-mono text-xs text-purple-400"
              >
                {t}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* Stats */}
      <section className="border-b border-gray-800 px-6 py-16">
        <div className="mx-auto max-w-5xl">
          <p className="mb-2 font-mono text-xs uppercase tracking-widest text-purple-400">// Scale</p>
          <h2 className="text-2xl font-bold md:text-3xl">Data Under Management</h2>
          <div className="mt-10 grid gap-6 md:grid-cols-3">
            {[
              { label: "Standard Words", value: "1,824" },
              { label: "Standard Terms", value: "5,875" },
              { label: "Column Definitions", value: "1,301" },
            ].map((stat) => (
              <div key={stat.label} className="rounded-xl border border-gray-700 bg-gray-900 p-6 text-center">
                <div className="text-4xl font-bold text-purple-400">{stat.value}</div>
                <div className="mt-2 text-sm text-gray-500">{stat.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Screenshots */}
      <section className="border-b border-gray-800 px-6 py-20">
        <div className="mx-auto max-w-5xl">
          <p className="mb-2 font-mono text-xs uppercase tracking-widest text-purple-400">// Screenshots</p>
          <h2 className="text-2xl font-bold md:text-3xl">App Preview</h2>
          <ScreenshotGallery screenshots={screenshots.map((s) => ({ ...s, width: 1920, height: 1080 }))} />
        </div>
      </section>

      {/* Architecture */}
      <section className="border-b border-gray-800 px-6 py-20">
        <div className="mx-auto max-w-5xl">
          <p className="mb-2 font-mono text-xs uppercase tracking-widest text-purple-400">// Architecture</p>
          <h2 className="text-2xl font-bold md:text-3xl">Design Decisions</h2>
          <div className="mt-10 grid gap-6 md:grid-cols-2">
            {features.map((f) => (
              <div
                key={f.title}
                className="rounded-xl border border-gray-700 bg-gray-900 p-6 transition-colors hover:border-purple-400/30"
              >
                <h3 className="font-semibold text-white">{f.title}</h3>
                <p className="mt-2 text-sm leading-relaxed text-gray-400">{f.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Challenges */}
      <section className="border-b border-gray-800 px-6 py-20">
        <div className="mx-auto max-w-5xl">
          <p className="mb-2 font-mono text-xs uppercase tracking-widest text-purple-400">// Challenges</p>
          <h2 className="text-2xl font-bold md:text-3xl">Key Challenges & Solutions</h2>
          <div className="mt-10 space-y-4">
            {challenges.map((c) => (
              <div key={c.title} className="rounded-xl border border-gray-700 bg-gray-900 p-6">
                <h3 className="font-semibold text-white">{c.title}</h3>
                <p className="mt-2 text-sm leading-relaxed text-gray-400">{c.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Tech Stack */}
      <section className="px-6 py-20">
        <div className="mx-auto max-w-5xl">
          <p className="mb-2 font-mono text-xs uppercase tracking-widest text-purple-400">// Tech Stack</p>
          <h2 className="text-2xl font-bold md:text-3xl">Technology Overview</h2>
          <div className="mt-10 grid gap-6 md:grid-cols-3">
            {stack.map((group) => (
              <div key={group.title} className="rounded-xl border border-gray-700 bg-gray-900 p-6">
                <h3 className="mb-4 font-semibold text-purple-400">{group.title}</h3>
                <ul className="space-y-2">
                  {group.items.map((item) => (
                    <li key={item} className="flex items-center gap-2 text-sm text-gray-400">
                      <span className="h-1.5 w-1.5 shrink-0 rounded-full bg-purple-500" />
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-gray-800 px-6 py-10 text-center">
        <p className="text-sm text-gray-600">
          © 2025 Dongjin Cho ·{" "}
          <Link href="/" className="cursor-pointer text-gray-500 transition-colors hover:text-purple-400">
            Portfolio
          </Link>
        </p>
      </footer>
    </div>
  );
}
